// Gear list data for Pack Ledger. Edit this file to add, remove or change items.
// Weights are in ounces (oz). See CLAUDE.md for the field guide.
window.PACK_ITEMS = [
  {id:"pack", cat:"base", role:"Pack", name:"Gorilla 50", brand:"Gossamer Gear", oz:31.9, img:"images/pack.jpg", note:"Published Medium weight. Size and year on your pack are unconfirmed.", on:true},
  {id:"tent", cat:"base", role:"Shelter", group:"shelter", fit:"contain", name:"Skyscape Trekker", brand:"Six Moon Designs", oz:28, img:"images/trekker.jpg", note:"Tent only. Needs two 45 in trekking poles, which are not counted here.", on:true},
  {id:"stakes", cat:"base", role:"Shelter", name:"6 Piece Stake Set", brand:"Six Moon Designs", oz:2.5, img:"images/stakes.jpg", note:"Six 7 in aluminum Y stakes with pull cords.", on:true},
  {id:"hammock", cat:"base", role:"Shelter", group:"shelter", alsoOff:["stakes"], name:"Mantis UL Hammock Tent", brand:"Kammok", oz:32, img:"images/mantis.jpg", note:"Includes rainfly, straps, bug net, and its own stakes. Checking it unchecks the tent and stake set.", on:false},
  {id:"bag", cat:"base", role:"Sleep", name:"Magma 30 (Men's Long)", brand:"REI Co-op", oz:22, img:"images/bag.jpg", note:"850-fill down, 30°F. Published weight is for the current version.", on:true},
  {id:"pad", cat:"base", role:"Sleep", name:"Ether Light XR Insulated, Large", brand:"Sea to Summit", oz:21.3, img:"images/pad.jpg", note:"Tapered version. The rectangular Large is 23.5 oz.", on:true},
  {id:"pillow", cat:"base", role:"Sleep", name:"Aeros Premium Pillow, XL", brand:"Sea to Summit", oz:8.8, img:"images/pillow.jpg", note:"Published weight, 250 g.", on:true},
  {id:"rab", cat:"clothing", role:"Rain layer", name:"Phantom Waterproof Jacket, XXL", brand:"Rab", oz:4.1, img:"images/rab.jpg", note:"Published weight is for size M. Your XXL is likely a little heavier, so weigh it.", on:true},
  {id:"stove", cat:"food", role:"Stove", fit:"contain", img:"images/stove.jpg", name:"Titanium Backpacking Stove", brand:"TOAKS", oz:1.7, note:"Stove only, 48 g. Uses isobutane-propane canisters (fuel not counted). Includes a storage bag.", on:true},
  {id:"pot", cat:"food", role:"Cook pot", fit:"contain", img:"images/pot.jpg", name:"Titanium 750 ml Pot", brand:"TOAKS", oz:3.6, note:"Listed at 3.6 oz. Sold as pot, lid, and mesh sack. Weigh it to confirm what that includes.", on:true},
  {id:"cup", cat:"food", role:"Cup", fit:"contain", img:"images/cup.jpg", name:"Light Titanium 450 ml Cup, Ultralight", brand:"TOAKS", oz:1.7, note:"48 g, no lid.", on:true},
  {id:"sleeves", cat:"clothing", role:"Compression", name:"Compression Leg Sleeves, L/XL", brand:"Zensah", oz:null, note:"Weight not published. Weigh the pair and enter it.", on:true},
  {id:"filter", cat:"misc", role:"Water filter", name:"BeFree Water Filtration System, 1 L", brand:"Katadyn", oz:2, img:"images/filter.jpg", fit:"contain", note:"Sportsman's Guide lists 2 oz for the 1 L size (3 L is 4 oz). Hollow-fiber filter, about 1,000 L life. Removes bacteria and protozoa, not viruses.", on:true},
  {id:"springmealblueberry", cat:"food", role:"Trail meal", fit:"contain", img:"images/blueberry.jpg", name:"Endurance Meal, Blueberry", brand:"Spring Energy", oz:3.9, note:"REI lists 110 g (about 3.9 oz) per pouch, 310 cal. Vegan.", on:true},
  {id:"springmealmatcha", cat:"food", role:"Trail meal", fit:"contain", img:"images/matcha.jpg", name:"Endurance Meal, Matcha Berry", brand:"Spring Energy", oz:3.9, note:"REI lists 110 g (about 3.9 oz) per pouch, 310 cal. Vegan, with natural caffeine.", on:true},
  {id:"springgel", cat:"food", role:"Energy gel", fit:"contain", img:"images/gel.jpg", name:"Energy Gel, Speednut with Caffeine", brand:"Spring Energy", oz:1.8, note:"52 g net weight per packet, 50 mg caffeine.", on:true},
  {id:"peakthai", cat:"food", role:"Backpacking meal", fit:"contain", img:"images/thai.jpg", name:"Thai Chicken Coconut Curry, 2 Servings", brand:"Peak Refuel", oz:5.4, note:"REI lists 5.4 oz net weight, 430 cal per serving.", on:true},
  {id:"peakchickenrice", cat:"food", role:"Backpacking meal", fit:"contain", img:"images/chickenrice.jpg", name:"Homestyle Chicken & Rice, 2 Servings", brand:"Peak Refuel", oz:5.15, note:"REI lists 5.15 oz net weight, 370 cal per serving.", on:true},
  {id:"peakbison", cat:"food", role:"Backpacking meal", fit:"contain", img:"images/bison.jpg", name:"Backcountry Bison Bowl, 2 Servings", brand:"Peak Refuel", oz:7.05, note:"REI lists 7.05 oz net weight, 460 cal per serving.", on:true},
  {id:"peakgoulash", cat:"food", role:"Backpacking meal", fit:"contain", img:"images/goulash.jpg", name:"American Buffalo Goulash, 2 Servings", brand:"Peak Refuel", oz:4.94, note:"Manufacturer lists 4.94 oz net weight, 740 cal total.", on:true},
  {id:"groundsheet", cat:"base", role:"Ground sheet", fit:"contain", img:"images/groundsheet.jpg", name:"Tent Ground Sheet", brand:"REI Co-op", oz:null, note:"Manufacture tag reads China, May 2018. Exact model discontinued, so no published weight. Weigh it and enter the reading.", on:true}
];
